version: '2.3'

services:
  main:
    container_name: ood-detection
    build:
      context: ./
      dockerfile: docker/main/Dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/env.env"
    volumes:
      - dataset:/dataset
      - nfs_shared:/nfs_shared
    ports:
      - "11000:8000"
      - "11022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
  lift:
    container_name: lift_map_detection
    build:
      context: ./
      dockerfile: docker/lift/Dockerfile
    env_file:
      - "docker/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - dataset:/dataset
      - nfs_shared:/nfs_shared
    stdin_open: true
    tty: true

volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      device: /home/mmlab/hdd
      o: bind
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"